import { Colors } from "@/theme/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "flex-start",
    backgroundColor: Colors.background,
    paddingTop: 10,
  },
  scroll: {
    flex: 1,
    width: "100%",
  },
  contentContainer: {
    paddingHorizontal: 20,
    paddingBottom: 32,
    paddingTop: 8,
    alignItems: "center",
  },
  contentSection: {
    width: "100%",
    marginBottom: 18,
    alignItems: "center",
  },
  headerIcon: {
    position: "absolute",
    left: 20,
    zIndex: 10,
  },
  card: {
    backgroundColor: Colors.white,
    borderRadius: 12,
    padding: 24,
    alignItems: "center",
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    width: "100%",
  },
  cardIcon: {
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 22,
    fontWeight: "bold",
    textAlign: "center",
    color: Colors.darkGray,
    marginBottom: 8,
  },
  cardSubtitle: {
    fontSize: 16,
    textAlign: "center",
    color: Colors.gray,
    marginBottom: 24,
    lineHeight: 24,
  },
  vehicleContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
  },
  vehicleCard: {
    backgroundColor: Colors.white,
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  vehicleIconContainer: {
    marginRight: 16,
  },
  vehicleInfoContainer: {
    flex: 1,
  },
  vehicleDataRow: {
    flexDirection: "row",
    marginBottom: 4,
  },
  vehicleDataLabel: {
    fontWeight: "bold",
    color: Colors.darkGray,
    marginRight: 8,
  },
  vehicleDataValue: {
    color: Colors.darkGray,
  },
  // --- Lista de veículos no padrão da tela VeiculosCliente ---
  vehicleItemCard: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 24,
    marginBottom: 16,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 4,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    width: "100%",
  },
  vehicleItemInfo: {
    flex: 1,
    marginRight: 10,
  },
  vehicleInfoRow: {
    flexDirection: "row",
    alignItems: "baseline",
    marginBottom: 6,
  },
  vehicleLabel: {
    fontSize: 14,
    fontWeight: "bold",
    color: Colors.primary,
    textAlign: "left",
    lineHeight: 20,
  },
  vehicleValue: {
    fontSize: 14,
    color: Colors.darkGray,
    fontWeight: "500",
    textAlign: "left",
    marginLeft: 6,
    flexShrink: 1,
    lineHeight: 20,
  },
  detailsButton: {
    flexShrink: 0,
    width: "auto",
    paddingHorizontal: 16,
    height: 44,
  },
  detailsButtonText: {
    fontSize: 14,
    fontWeight: "bold",
    color: Colors.white,
  },
});
